const mongoose = require('mongoose');

const PlantSchema = new mongoose.Schema({
  id: Number,
  common_name: String,
  scientific_name: [String],
  other_name: [String],
  family: String,
  origin: [String],
  type: String,
  dimension: String,
  dimensions: {
    type: String,
    min_value: Number,
    max_value: Number,
    unit: String,
  },
  cycle: String,
  attracts: [String],
  propagation: [String],
  hardiness: {
    min: String,
    max: String,
  },
  hardiness_location: {
    full_url: String,
    full_iframe: String,
  },
  watering: String,
  depth_water_requirement: {
    unit: String,
    value: String,
  },
  volume_water_requirement: [String],
  watering_period: String,
  watering_general_benchmark: {
    value: String,
    unit: String,
  },
  plant_anatomy: [{
    part: String,
    color: [String],
  }],
  sunlight: [String],
  pruning_month: [String],
  pruning_count: [String],
  seeds: Number,
  maintenance: String,
  care_guides: String,
  soil: [String],
  growth_rate: String,
  drought_tolerant: Boolean,
  salt_tolerant: Boolean,
  thorny: Boolean,
  invasive: Boolean,
  tropical: Boolean,
  indoor: Boolean,
  care_level: String,
  pest_susceptibility: [String],
  pest_susceptibility_api: String,
  flowers: Boolean,
  flowering_season: String,
  flower_color: String,
  cones: Boolean,
  fruits: Boolean,
  edible_fruit: Boolean,
  edible_fruit_taste_profile: String,
  fruit_nutritional_value: String,
  fruit_color: [String],
  harvest_season: String,
  leaf: Boolean,
  leaf_color: [String],
  edible_leaf: Boolean,
  cuisine: Boolean,
  medicinal: Boolean,
  poisonous_to_humans: Number,
  poisonous_to_pets: Number,
  description: String,
  default_image: {
    license: Number,
    license_name: String,
    license_url: String,
    original_url: String,
    regular_url: String,
    medium_url: String,
    small_url: String,
    thumbnail: String,
  },
  other_images: String,
});

module.exports = mongoose.model('Plant', PlantSchema);
